Cheatsheet {data-orientation=columns}
=======================================================================

Column
-----------------------------------------------------------------------

### R Links

- [Dash from Plotly](https://dash-gallery.plotly.host/Portal/)

- [R-Markdown Dashboard](https://rmarkdown.rstudio.com/lesson-12.html) | [R-Markdown Webstie](https://rmarkdown.rstudio.com/rmarkdown_websites.html)

- [R-Markdown Styling](https://rmarkdown.rstudio.com/html_document_format.html#appearance_and_style) | [Bootstrap Themes](https://bootswatch.com/)

- [Shiny Server Manual](http://docs.rstudio.com/shiny-server/)

### R Tidyverse

Modify, Subset, Keep/Drop, Extract, Summarize
<p><pre>
datatable %>% 
  mutate(new_var = fun(old_vars)) %>%
  filter(var = cond) %>%
  select(var1, var2) %>%  
  pull(var1) %>% 
  summarize_at(c("var1", "var2"), fun)
</pre></p>

### SAS Proceedings List

20MAR Summary on Mixed Models

27MAR [Proc SQL | Macro Var & SQL](#section-proc-sql)

03APR Subroutines and SAS functions

10APR Functions and PROC IMPL (continued)

17APR [Advanced topics of arrary, vname and do over](#section-arrayformat)

24APR Oncology Pharma 

02MAY [Proc Formats as a life-changer](#section-arrayformat)

09MAY Oncology continued

00JUL SAS Project organization and SVN exploration

12AUG [Optimizing SAS EG's speed](#https://support.sas.com/resources/papers/proceedings14/SAS331-2014.pdf)

14AUG [Proc Corresp](https://support.sas.com/documentation/cdl/en/statug/63347/HTML/default/viewer.htm#statug_corresp_sect005.htm)

### Characters

潘䶮(4dae)

潘(e863)

Column
-----------------------------------------------------------------------

### SAS Documentations

- [SAS Procedures](https://go.documentation.sas.com/?cdcId=pgmsascdc&cdcVersion=9.4_3.4&docsetId=allprodsproc&docsetTarget=procedures.htm&locale=en) | [SAS Data Steps](https://go.documentation.sas.com/?cdcId=pgmsascdc&cdcVersion=9.4_3.4&docsetId=lestmtsref&docsetTarget=p08st7rzfn0dgin1fml8hq40hlho.htm&locale=en)

- [Functions](https://go.documentation.sas.com/?cdcId=pgmsascdc&cdcVersion=9.4_3.4&docsetId=lefunctionsref&docsetTarget=n01f5qrjoh9h4hn1olbdpb5pr2td.htm&locale=en)

- [PROC tabulate](http://support.sas.com/resources/papers/proceedings09/039-2009.pdf)

### PROC output styles

<p><pre>
PROC MEANS noprint data=input;
	by cohort; var bmi;
	output out = output (drop = _freq_ _type_);
PROC FREQ data=input
  table var1 * var2 / out = output;
RUN;
</pre></p>

ODS output can be accessed by enable trace

<p><pre>
ods trace on; 
...; ods output a = name;
</pre></p>

Column
-----------------------------------------------------------------------

### CDISC.org References

- [SDTM v1.7](https://www.cdisc.org/standards/foundational/sdtm/sdtm-v1-7) | [SDTMIG v3.3](https://www.cdisc.org/standards/foundational/sdtmig/sdtmig-v3-3) | [v3.2 pdf](https://www.cdisc.org/system/files/members/standard/foundational/sdtmig/sdtmig_20v3.2_20noportfolio.pdf)

- [ADaM v2.1](https://www.cdisc.org/system/files/members/standard/foundational/adam/analysis_data_model_v2.1.pdf) | [ADaMIG v1.1](https://www.cdisc.org/system/files/members/standard/foundational/adam/ADaMIG_v1.1.pdf) | [ADaM OCCDS v1.0](https://www.cdisc.org/system/files/members/standard/foundational/adam/ADaM_OCCDS_v1.0.pdf) | [ADaM Examples](https://www.cdisc.org/system/files/members/standard/foundational/adam/adam_examples_final.pdf)


- [Controlled Terminology](https://evs.nci.nih.gov/ftp1/CDISC/SDTM/SDTM%20Terminology.html)

- [CDISC Glossary](https://www.cdisc.org/system/files/members/standard/foundational/glossary/CDISC%20Glossary%20v11.pdf)


### STDM Keys

[relative timing](https://www.cdisc.org/standards/foundational/sdtmig/sdtmig-v3-3#Use+of+Relative+Timing+Variables) | --STRF -- ENRF --STRTPT --STTPT --ENRTPT --ENTPT 
<br />
BEFORE DURING DURING/AFTER AFTER U (=unkonwn) Ongoing Prior

### ADaM Keys

w=[1-9] xx=[01-99] y=[1-99] zz=[01-99]

<p><pre>
-N	  converted from character to numeric, e.g. SEXN
-FL	  flag, non-missing "Y" or "N"
-DT   staring dates, -EDTM end datetimes, -STM  start times
-DTF  imputation flag for datetimes
-GRy  gourping vars
A-	  analysis-ready vars, with proper imputation
</pre></p>

### Steps to determine BDS ADaM

1. from source (SDTM), creation of PARAM, AVISIT, AVAL, AVALC, plus identifiers and traceability;

2. adding derived rows or column, based on rules:

-- Rule 1: new column if fun(AVAL, BASE), fun is parameter-invariant, NO transform of BASE<br />
-- Rule 2: new row (i.e. PARAM, AVAL) if not rule 1<br />
-- Rule 3-4: new row if fun(multiple rows)<br />
-- Rule 5:  new row if fun(multiple params)<br />
-- Rule 6: new row for different baseline definitions
