---
title: "Moi!"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
runtime: shiny
---

```{r setup, include=FALSE}
library(visNetwork)
library(flexdashboard)
library(shiny)
library(tidyverse)
library(DT)

getDataType <- function(type = c("char")){
  result <- NULL
  for(i in 1:length(type)){
    if(type[i] == "Char") result <- c(result, "Char(200)")
    else if(type[i] == "Num") result <- c(result, "Num(10)")
    else result <- c(result, "/*ERROR*/")
  }
  result
}
```

Cheatsheet
=======================================================================

Column
-----------------------------------------------------------------------

### SAS Documentations

- [SAS Procedures](https://go.documentation.sas.com/?cdcId=pgmsascdc&cdcVersion=9.4_3.4&docsetId=allprodsproc&docsetTarget=procedures.htm&locale=en)

- [SAS Data Steps](https://go.documentation.sas.com/?cdcId=pgmsascdc&cdcVersion=9.4_3.4&docsetId=lestmtsref&docsetTarget=p08st7rzfn0dgin1fml8hq40hlho.htm&locale=en)

- [Functions](https://go.documentation.sas.com/?cdcId=pgmsascdc&cdcVersion=9.4_3.4&docsetId=lefunctionsref&docsetTarget=n01f5qrjoh9h4hn1olbdpb5pr2td.htm&locale=en)

[SAS EG Keyboard](http://support.sas.com/documentation/cdl/en/hostwin/69955/HTML/default/viewer.htm#p0726xzb9e7fp7n1sjiml5m2cedu.htm)

### Working with Formats


<pre>
ENDDT = input(substr(str, 1, 10), yymmdd10.);
format ENDDT yymmdd10.;
ADY = intck('day', STARTDT, ENDDT);
</pre>


### PROC output styles

<pre>
PROC MEANS noprint data=input;
	var bmi;
	by cohort;
	output out = output (drop = _freq_ _type_);
PROC FREQ data=input
  table var1 * var2 / out = output;
RUN;
</pre>

### PROC Transpose wide->long

<pre>
PROC TRANSPOSE data=input 
               out=output (drop=_NAME_ _label_);
	by cohort;
	id _stat_;
RUN;
</pre>



Column
-----------------------------------------------------------------------

### Some Cheatsheet here

N/A

Column
-----------------------------------------------------------------------

### CDISC.org References

- [SDTMIG v3.3](https://www.cdisc.org/standards/foundational/sdtmig/sdtmig-v3-3) | [v3.2 pdf](https://www.cdisc.org/system/files/members/standard/foundational/sdtmig/sdtmig_20v3.2_20noportfolio.pdf)

- [SDTM v1.7](https://www.cdisc.org/standards/foundational/sdtm/sdtm-v1-7)

- [SDTM Controlled Terminology](https://evs.nci.nih.gov/ftp1/CDISC/SDTM/SDTM%20Terminology.html)

- [CDISC Glossary](https://www.cdisc.org/system/files/members/standard/foundational/glossary/CDISC%20Glossary%20v11.pdf)

<center>
[AE](https://www.cdisc.org/standards/foundational/sdtmig/sdtmig-v3-3#Adverse+Events) | [EX](https://www.cdisc.org/standards/foundational/sdtmig/sdtmig-v3-3#Exposure)
</center>

### Nothing

```{r}
renderPrint("nothing to show yet")
```

GCP...
=======================================================================

Column
-----------------------------------------------------------------------

### SDTM at a Glance

```{r}
keys <- c("Data Class", "Variable Roles", "Core Variables")

grp01 <- data.frame(id = 1:3,
                   label = keys,
                   title = c("define tables", "define variables", "some "),
                   group = keys,
                   shape = c("database", "circle", "star"))
grp11 <- data.frame(id = 11:16,
                   label = c("Inteventions",  "Events", "Findings", "Domain", "Trial Design", "Relationship"),
                   title = NA,
                   group = keys[1],
                   shape = "ellipse")
grp12 <- data.frame(id = 21:24,
                   label = c("Identifier", "Topic", "Timing", "Qualifier"),
                   title = NA,
                   group = keys[2],
                   shape = "ellipse")
grp13 <- data.frame(id = 31:33,
                   label = c("Required", "Expected", "Permissible"),
                   title = NA,
                   group = keys[3], 
                   shape = "text")
grp21 <- data.frame(id = 101:114,
                   label = c("CM", "EX", "AE", "DS", "VS", "PE", "DM", "CO", "SV", "TA", "TI", "TV", "RELREC", "SUPP--"),
                   title = c("CM Conmeds", "EX Exposure", "AE Adverse Events", "DS Disposition Events", "VS Vital Signs", "PE Pysical Exam", "DM Demographics", "CO Comments", "SV Subject Visits", "TA Trial Arms", "TI Trial Inclusion", "TV Trial Visits", "RELREC Related Records", "SUPP-- Supplemental Qualifiers"),
                   group = "- tables",
                   shape = "box")
grp22 <- data.frame(id = 201:212,
                    label = c("STUDYID", "USUBJID", "--SEQ", "LBTEST", "AETERM", "CMTRT", "LBDTC", "AESTDTC", "EXENDTC", "LBORRES", "AESEV", "CMDOSE"),
                    title = c("STUDYID Study ID", "USUBJID Subject ID", "--SEQ Sequence ID", "LBTEST Lab Test Name", "AETERM Adverse Event Term", "CMTRT Reported Drug Name", "LBDTC Lab Assessment Date", "AESTDTC Adverse Event Start Date", "EXENDTC Exposure End Date", "LBORRES Lab Test Result", "AESEV Adverse Event Severity", "CMDOSE Conmed Dose"),
                    group = "- variables",
                    shape = "box")

nodes <- rbind(grp01, grp11, grp12, grp13, grp21, grp22)
edges <- data.frame(from = c(rep(1, 6), rep(2, 4), rep(3, 3),
                             rep(11,2), rep(12,2), rep(13,2), rep(14,3), rep(15,3), rep(16,2),
                             rep(21,3), rep(22,3), rep(23,3), rep(24,3)),
                    to   = c(11:16, 21:24, 31:33,
                             101:114,
                             201:212))

visNetwork(nodes, edges, width = "100%", height = "400px") %>%
  visOptions(highlightNearest = list(enabled = T, hover = T), 
             selectedBy = "group")  %>%
  visLayout(randomSeed = 69)
```

Column
-----------------------------------------------------------------------

### Something to Cover

to be furnished


SDTM {style="position:relative; height:auto"}
=======================================================================

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
tables <- readRDS("sdtm_domain.rds")
catlog <- tables[[1]]

selectInput("sdtm_domain", "Domains", choices = sort(catlog$Name))

renderText(paste(nrow(tables[[catlog$index[which(catlog$Name == input$sdtm_domain)]]]), "variables"))
```

<hr />

```{r}
checkboxGroupInput("sdtm_core", "Generate SQL", choices = c("Req", "Perm", "Exp"), selected = c("Req", "Exp"))

renderPrint(
  tables[[catlog$index[which(catlog$Name == input$sdtm_domain)]]] %>% 
    filter(Core %in% input$sdtm_core) %>%
    mutate(Sql = paste0('/*',pull(.,7) ,'*/\t',pull(.,1), " ", getDataType(pull(., 3)), ' "', pull(., 2), '"')) %>%
    pull(Sql) %>% 
    paste(collapse = ", \n") %>%
    cat()
)
```

Retain (all variables)

```{r}
renderPrint(
  tables[[catlog$index[which(catlog$Name == input$sdtm_domain)]]] %>%
    pull(1) %>%
    paste(collapse = " ")
)
```

<hr />

Based on [SDTMIG v3.3](https://www.cdisc.org/standards/foundational/sdtmig/sdtmig-v3-3)

Column {style="height:auto; min-height: 300pc; overflow: auto;"}
-----------------------------------------------------------------------

### Tables

```{r}
renderDT(tables[[catlog$index[which(catlog$Name == input$sdtm_domain)]]],
                    options = list(pageLength = 50, dom = 'lfpt'))
```

end.